/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;

import java.io.FileReader;
import java.io.IOException;


public class App {


    public static void main(String[] args) throws IOException {
        Gson gson = new Gson();
        File file = new File("app/src/test/resources/quotes.json");
        FileReader reader = new FileReader(file);
        Quote[] fileString =  gson.fromJson(reader, Quote[].class);
        int arrayLength = fileString.length;
        int rando = (int)(Math.random() * arrayLength);
        System.out.println(fileString[rando]);

    }
}
